Classes Test:
new SimpleClass ()
new DerivedClass ()
new PublicClass ()
new ClassWithCreationMethod ()
ClassWithCreationMethod
new ClassWithNamedCreationMethod ()
ClassWithNamedCreationMethod
new ClassWithDestructor ()
~ClassWithDestructor
new SimpleGTypeInstanceClass ()
new DerivedGTypeInstanceClass ()
new PublicGTypeInstanceClass ()
new GTypeInstanceClassWithCreationMethod ()
GTypeInstanceClassWithCreationMethod
new GTypeInstanceClassWithNamedCreationMethod ()
GTypeInstanceClassWithNamedCreationMethod
new SimpleGObjectClass ()
new DerivedGObjectClass ()
new PublicGObjectClass ()
new GObjectClassWithCreationMethod ()
new GObjectClassWithNamedCreationMethod ()
new SimpleClass () { field = 1 }
simple_class.field = 1
.
