.TH vapigen 1 "13 April 2010" "vala-0.8.0" "Vala"
.IX vapigen
.SH NAME
vapigen \- generate a Vala API
.SH SYNOPSIS
.B vapigen \fISOURCE\fP \fIPKGBASE\fP
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B vapigen
is a utility which generates Vala API (VAPI) files from GI files,
which may be generated using the vala-gen-introspect(1) utility.

.SH EXAMPLES
.TP
After compilation, the following command generates a GI for pango:
.B vala-gen-introspect pango packages/pango
.TP
This can then be converted to a Vala API as follows:
.B vapigen --pkg cairo --vapidir . --library pango packages/pango/pango.gi

.SH OPTIONS
.TP
.B \-?, --help
Show help option
.TP
.B \--vapidir=\fIDIRECTORY\fP
Look for package bindings in \fIDIRECTORY\fP.
.TP
.B \--girdir=\fIDIRECTORY\fP
Look for GIR bindings in \fIDIRECTORY\fP.
.TP
.B \--metadatadir=\fIDIRECTORY\fP
Look for GIR .metadata files in \fIDIRECTORY\fP.
.TP
.B \--pkg=\fIPACKAGE\fP
Include binding for \fIPACKAGE\fP
.TP
.B \--library=\fINAME\fP
Specify library name as \fINAME\fP
.TP
.B \-d, --directory=\fIDIRECTORY\fP
Specify output directory as \fIDIRECTORY\fP
.TP
.B \--version
Display version number and exit.
.TP
.B \-q, --quiet
Do not print messages to the console

.SH SEE ALSO
.BR vala-gen-introspect (1)

.SH HOMEPAGE AND BUG REPORT
http://www.vala-project.org/

.SH AUTHOR
vapigen for Vala was written by Jürg Billeter <j@bitron.ch> and
Raffaele Sandrini <rasa@gmx.ch>.
.PP
This manual page was written by Kumar Appaiah <akumar@ee.iitm.ac.in>,
for the Debian project (but may be used by others).
