/* gstreamer-netbuffer-0.10.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "Gst", lower_case_cprefix = "gst_")]
namespace Gst {
	[CCode (cheader_filename = "gst/netbuffer/gstnetbuffer.h")]
	public class NetBuffer : Gst.Buffer {
		public weak Gst.Buffer buffer;
		public Gst.NetAddress from;
		public Gst.NetAddress to;
		[CCode (cname = "gst_netbuffer_new", has_construct_function = false)]
		public NetBuffer ();
	}
	[Compact]
	[CCode (cheader_filename = "gst/netbuffer/gstnetbuffer.h")]
	public class NetBufferClass {
		public weak Gst.BufferClass buffer_class;
	}
	[CCode (type_id = "GST_TYPE_NET_ADDRESS", cheader_filename = "gst/netbuffer/gstnetbuffer.h")]
	public struct NetAddress {
		public Gst.NetType type;
		public void* address;
		public uint16 port;
		[CCode (cname = "gst_netaddress_get_ip4_address")]
		public bool get_ip4_address (out uint32 address, out uint16 port);
		[CCode (cname = "gst_netaddress_get_ip6_address")]
		public bool get_ip6_address ([CCode (array_length = false)] uchar[] address, out uint16 port);
		[CCode (cname = "gst_netaddress_get_net_type")]
		public Gst.NetType get_net_type ();
		[CCode (cname = "gst_netaddress_set_ip4_address")]
		public void set_ip4_address (uint32 address, uint16 port);
		[CCode (cname = "gst_netaddress_set_ip6_address")]
		public void set_ip6_address ([CCode (array_length = false)] uchar[] address, uint16 port);
	}
	[CCode (cprefix = "GST_NET_TYPE_", has_type_id = "0", cheader_filename = "gst/netbuffer/gstnetbuffer.h")]
	public enum NetType {
		UNKNOWN,
		IP4,
		IP6
	}
}
