Classes Test:
new CompactClass ()
new DerivedClass ()
new PublicClass ()
new ClassWithCreationMethod ()
ClassWithCreationMethod
new ClassWithNamedCreationMethod ()
ClassWithNamedCreationMethod
new CompactClassWithDestructor ()
~CompactClassWithDestructor
new SimpleGTypeInstanceClass ()
new DerivedGTypeInstanceClass ()
new PublicGTypeInstanceClass ()
new GTypeInstanceClassWithCreationMethod ()
GTypeInstanceClassWithCreationMethod
new GTypeInstanceClassWithNamedCreationMethod ()
GTypeInstanceClassWithNamedCreationMethod
new SimpleGObjectClass ()
new DerivedGObjectClass ()
new PublicGObjectClass ()
new GObjectClassWithCreationMethod ()
new GObjectClassWithNamedCreationMethod ()
new CompactClass () { field = 1 }
compact_class.field = 1
.
