void main () {
#if !GLIB_2_16
	assert_not_reached ();
#elif !GLIB_2_18
	assert_not_reached ();
#elif !GLIB_2_18
	assert_not_reached ();
#elif !GLIB_2_20
	assert_not_reached ();
#elif !GLIB_2_22
	assert_not_reached ();
#elif !GLIB_2_24
	assert_not_reached ();
#elif !GLIB_2_26
	assert_not_reached ();
#elif !GLIB_2_28
	assert_not_reached ();
#elif !GLIB_2_30
	assert_not_reached ();
#elif !GLIB_2_32
	assert_not_reached ();
#elif !GLIB_2_34
	assert_not_reached ();
#elif !GLIB_2_36
	assert_not_reached ();
#elif !GLIB_2_38
	assert_not_reached ();
#elif !GLIB_2_40
	assert_not_reached ();
#elif !GLIB_2_42
	assert_not_reached ();
#elif !GLIB_2_44
	assert_not_reached ();
#elif !GLIB_2_46
	assert_not_reached ();
#elif !GLIB_2_48
	assert_not_reached ();
#elif !GLIB_2_50
	assert_not_reached ();
#elif !GLIB_2_52
	assert_not_reached ();
#elif !GLIB_2_54
	assert_not_reached ();
#elif !GLIB_2_56
	assert_not_reached ();
#else
	assert (true);
#endif
}
