void main () {
#if !VALA_0_2
	assert_not_reached ();
#elif !VALA_0_4
	assert_not_reached ();
#elif !VALA_0_6
	assert_not_reached ();
#elif !VALA_0_8
	assert_not_reached ();
#elif !VALA_0_10
	assert_not_reached ();
#elif !VALA_0_12
	assert_not_reached ();
#elif !VALA_0_14
	assert_not_reached ();
#elif !VALA_0_16
	assert_not_reached ();
#elif !VALA_0_18
	assert_not_reached ();
#elif !VALA_0_20
	assert_not_reached ();
#elif !VALA_0_22
	assert_not_reached ();
#elif !VALA_0_24
	assert_not_reached ();
#elif !VALA_0_26
	assert_not_reached ();
#elif !VALA_0_28
	assert_not_reached ();
#elif !VALA_0_30
	assert_not_reached ();
#elif !VALA_0_32
	assert_not_reached ();
#elif !VALA_0_34
	assert_not_reached ();
#elif !VALA_0_36
	assert_not_reached ();
#elif !VALA_0_38
	assert_not_reached ();
#elif !VALA_0_40
	assert_not_reached ();
#elif !VALA_0_42
	assert_not_reached ();
#elif !VALA_0_44
	assert_not_reached ();
#elif !VALA_0_46
	assert_not_reached ();
#elif !VALA_0_48
	assert_not_reached ();
#else
	assert (true);
#endif
}
